USE SiigoRent;
GO
ALTER VIEW dbo.vw_rentabilidad_zona7
AS
WITH x AS (
    SELECT
        REPLACE(REPLACE(CONVERT(nvarchar(4000), DESCRIPCION),
            NCHAR(129), NCHAR(209)), NCHAR(169), NCHAR(209)) AS DESCRIPCION,
        CASE WHEN LEFT(DOCUMENTO, 1) = 'J' THEN -CANTIDAD ELSE CANTIDAD END AS CANTIDAD,
        CASE WHEN LEFT(DOCUMENTO, 1) = 'J' THEN -Ventas ELSE Ventas END AS VENTAS,
        CASE WHEN LEFT(DOCUMENTO, 1) = 'J' THEN -Costos ELSE Costos END AS COSTOS,
        DOCUMENTO, FECHA, VendedorMov AS VENDEDOR
    FROM dbo.vw_rentabilidad_base
    WHERE ZonaVen = 7
), g AS (
    SELECT FECHA, DESCRIPCION, SUM(CANTIDAD) AS CANTIDAD,
        SUM(VENTAS) AS VENTAS, SUM(COSTOS) AS COSTOS
    FROM x
    GROUP BY FECHA, DESCRIPCION
    HAVING ABS(SUM(VENTAS)) >= 0.01 OR ABS(SUM(COSTOS)) >= 0.01
        OR ABS(SUM(CANTIDAD)) >= 0.0001
), docs AS (
    SELECT FECHA, DESCRIPCION,
        STRING_AGG(CONVERT(varchar(max), DOCUMENTO), ' | ')
            WITHIN GROUP (ORDER BY DOCUMENTO) AS DOCUMENTO
    FROM (SELECT DISTINCT FECHA, DESCRIPCION, DOCUMENTO FROM x) d
    GROUP BY FECHA, DESCRIPCION
), vens AS (
    SELECT FECHA, DESCRIPCION,
        STRING_AGG(CONVERT(varchar(max), VENDEDOR), ' | ')
            WITHIN GROUP (ORDER BY VENDEDOR) AS VENDEDOR
    FROM (SELECT DISTINCT FECHA, DESCRIPCION, VENDEDOR FROM x) v
    GROUP BY FECHA, DESCRIPCION
), vens_total AS (
    SELECT FECHA,
        STRING_AGG(CONVERT(varchar(max), VENDEDOR), ' | ')
            WITHIN GROUP (ORDER BY VENDEDOR) AS VENDEDOR
    FROM (SELECT DISTINCT FECHA, VENDEDOR FROM x) v
    GROUP BY FECHA
)
SELECT
    '0004   TIENDA PINTUCO' AS [CENTRO DE COSTO],
    g.DESCRIPCION, g.CANTIDAD, g.VENTAS, g.COSTOS,
    CAST(100.0 * (1 - g.COSTOS / NULLIF(g.VENTAS, 0.0)) AS decimal(18,2)) AS [% RENTA],
    CAST(100.0 * (g.VENTAS / NULLIF(g.COSTOS, 0.0) - 1) AS decimal(18,2)) AS [% UTIL],
    d.DOCUMENTO, g.FECHA, v.VENDEDOR
FROM g
LEFT JOIN docs d ON d.FECHA = g.FECHA AND d.DESCRIPCION = g.DESCRIPCION
LEFT JOIN vens v ON v.FECHA = g.FECHA AND v.DESCRIPCION = g.DESCRIPCION
UNION ALL
SELECT
    'TOTAL TIENDA PINTUCO (ZONA 7)', N'',
    SUM(g.CANTIDAD), SUM(g.VENTAS), SUM(g.COSTOS),
    CAST(100.0 * (1 - SUM(g.COSTOS) / NULLIF(SUM(g.VENTAS), 0.0)) AS decimal(18,2)),
    CAST(100.0 * (SUM(g.VENTAS) / NULLIF(SUM(g.COSTOS), 0.0) - 1) AS decimal(18,2)),
    '', g.FECHA, MAX(v.VENDEDOR)
FROM g
LEFT JOIN vens_total v ON v.FECHA = g.FECHA
GROUP BY g.FECHA;
GO
SELECT [CENTRO DE COSTO], CANTIDAD, VENTAS, COSTOS, [% RENTA], [% UTIL]
FROM dbo.vw_rentabilidad_zona7
WHERE FECHA = '20261006'
  AND [CENTRO DE COSTO] LIKE 'TOTAL%';
