int checks = 0;
void Check(bool value, string name) { if (!value) throw new Exception(name); checks++; }
var job = new EtlJobConfig { Kind = EtlJobKind.Rentabilidad, AtTime = "05:00" };
var now = DateTimeOffset.Parse("2026-10-07T10:00:00Z");
var state = new JobState();
Check(!RentabilidadClock.IsDue(job, state, now.AddMinutes(-1)), "antes de las 5");
Check(RentabilidadClock.IsDue(job, state, now), "5 Colombia");
Check(RentabilidadClock.IsDue(job, state, now.AddHours(5)), "recuperar horario perdido");
state.IsRunning = true;
Check(!RentabilidadClock.IsDue(job, state, now), "no concurrencia");
state.IsRunning = false; state.LastSuccessUtc = now;
Check(!RentabilidadClock.IsDue(job, state, now.AddHours(2)), "no repetir exito hoy");
state.LastSuccessUtc = now.AddDays(-1); state.LastRunUtc = now.AddMinutes(-10);
Check(!RentabilidadClock.IsDue(job, state, now), "esperar retry");
state.LastRunUtc = now.AddMinutes(-15);
Check(RentabilidadClock.IsDue(job, state, now), "retry a 15min");
state.ReportAttemptDay = new DateOnly(2026,10,7); state.ReportAttempts = 3;
Check(!RentabilidadClock.IsDue(job, state, now), "maximo 3 intentos");
Check(RentabilidadClock.IsDue(job, state, now.AddDays(1)), "reset siguiente dia");
state = new JobState { LastSuccessUtc = DateTimeOffset.Parse("2026-10-07T01:00:00Z") };
Check(RentabilidadClock.IsDue(job, state, now), "exito UTC del dia anterior colombiano");
var config = new AppConfig();
config.Jobs.Add(new EtlJobConfig { Name = "Carga", AtTime = "20:30" });
job.Rentabilidad.DependsOn.Add("Carga");
var serviceState = new ServiceState();
var worker = new Worker(Microsoft.Extensions.Logging.Abstractions.NullLogger<Worker>.Instance,
    new Microsoft.Extensions.Configuration.ConfigurationBuilder().Build());
var flags = System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic;
typeof(Worker).GetField("_cfg", flags)!.SetValue(worker, config);
typeof(Worker).GetField("_state", flags)!.SetValue(worker, serviceState);
var method = typeof(Worker).GetMethod("ShouldRunRentabilidad", flags)!;
bool Due() => (bool)method.Invoke(worker, new object[] { job, new JobState(), now })!;
Check(!Due(), "esperar dependencia faltante");
var dep = serviceState.GetOrCreate("Carga");
dep.LastSuccessUtc = DateTimeOffset.Parse("2026-10-06T22:00:00Z");
Check(!Due(), "esperar carga nocturna del dia anterior");
dep.LastSuccessUtc = DateTimeOffset.Parse("2026-10-07T01:35:00Z");
Check(Due(), "carga previa completa");
dep.LastErrorUtc = dep.LastSuccessUtc.Value.AddMinutes(1);
Check(!Due(), "fallo posterior pendiente de resolver");
job.Rentabilidad.FirstReportDate = "2026-10-07";
Check(!RentabilidadClock.IsDue(job, new JobState(), now), "no solicitar precios previos al primer cierre");
Check(RentabilidadClock.IsDue(job, new JobState(), now.AddDays(1)), "primer dia respaldado");
job.Kind = EtlJobKind.Productos;
job.AtTime = "20:45";
Check(!RentabilidadClock.IsDue(job, new JobState(), DateTimeOffset.Parse("2026-10-08T01:44:00Z")), "productos antes del cierre");
Check(RentabilidadClock.IsDue(job, new JobState(), DateTimeOffset.Parse("2026-10-08T01:45:00Z")), "productos independientes a las 20:45");
job.AtTime = "05:00";
var productsNow = DateTimeOffset.Parse("2026-10-08T01:45:00Z");
state = new JobState();
dep.LastErrorUtc = null;
dep.LastSuccessUtc = DateTimeOffset.Parse("2026-10-07T01:35:00Z");
Check(!(bool)method.Invoke(worker, new object[] { job, state, productsNow })!, "productos esperan carga de hoy");
dep.LastSuccessUtc = DateTimeOffset.Parse("2026-10-08T01:35:00Z");
Check((bool)method.Invoke(worker, new object[] { job, state, productsNow })!, "productos con catalogos de hoy completos");
var validationConfig = new AppConfig();
var disabled = new EtlJobConfig { Name = "Nuevo", Kind = EtlJobKind.Rentabilidad, Enabled = false };
validationConfig.Jobs.Add(disabled);
typeof(Worker).GetField("_cfg", flags)!.SetValue(worker, validationConfig);
var validate = typeof(Worker).GetMethod("ValidateConfiguration", flags)!;
validate.Invoke(worker, null);
Check(true, "trabajo deshabilitado no valida rutas ni detiene el ETL");
disabled.Enabled = true;
try { validate.Invoke(worker, null); throw new Exception("Debe validar al activar"); }
catch (System.Reflection.TargetInvocationException) { Check(true, "trabajo activo valida requisitos"); }
Console.WriteLine($"{checks} comprobaciones de servicio pasaron.");
